# База персонажей Naruto с рейтингами по ролям (1–100)
# captain, vice, support, healer, tank

NARUTO_CHARACTERS = [
    {"name": "Малик Жалмурзин", "village": "Кайнар", "ratings": {"captain": 100, "vice": 100, "support": 100, "healer": 100, "tank": 100}},
    {"name": "Наруто Узумаки", "village": "Коноха", "ratings": {"captain": 95, "vice": 90, "support": 75, "healer": 35, "tank": 88}},
    {"name": "Саске Учиха", "village": "Коноха", "ratings": {"captain": 92, "vice": 94, "support": 70, "healer": 30, "tank": 72}},
    {"name": "Сакура Харуно", "village": "Коноха", "ratings": {"captain": 78, "vice": 75, "support": 65, "healer": 95, "tank": 82}},
    {"name": "Какаши Хатаке", "village": "Коноха", "ratings": {"captain": 96, "vice": 93, "support": 88, "healer": 45, "tank": 80}},
    {"name": "Хината Хьюга", "village": "Коноха", "ratings": {"captain": 72, "vice": 70, "support": 68, "healer": 40, "tank": 65}},
    {"name": "Shikamaru Nara", "village": "Коноха", "ratings": {"captain": 90, "vice": 88, "support": 92, "healer": 35, "tank": 55}},
    {"name": "Choji Akimichi", "village": "Коноха", "ratings": {"captain": 68, "vice": 65, "support": 60, "healer": 30, "tank": 90}},
    {"name": "Ino Yamanaka", "village": "Коноха", "ratings": {"captain": 70, "vice": 68, "support": 85, "healer": 55, "tank": 50}},
    {"name": "Kiba Inuzuka", "village": "Коноха", "ratings": {"captain": 65, "vice": 62, "support": 58, "healer": 25, "tank": 70}},
    {"name": "Shino Aburame", "village": "Коноха", "ratings": {"captain": 68, "vice": 65, "support": 82, "healer": 40, "tank": 60}},
    {"name": "Rock Lee", "village": "Коноха", "ratings": {"captain": 75, "vice": 72, "support": 45, "healer": 20, "tank": 85}},
    {"name": "Neji Hyuga", "village": "Коноха", "ratings": {"captain": 82, "vice": 85, "support": 70, "healer": 35, "tank": 78}},
    {"name": "Tenten", "village": "Коноха", "ratings": {"captain": 62, "vice": 60, "support": 72, "healer": 30, "tank": 55}},
    {"name": "Gaara", "village": "Суна", "ratings": {"captain": 90, "vice": 88, "support": 75, "healer": 40, "tank": 92}},
    {"name": "Kankuro", "village": "Суна", "ratings": {"captain": 70, "vice": 68, "support": 80, "healer": 25, "tank": 65}},
    {"name": "Temari", "village": "Суна", "ratings": {"captain": 78, "vice": 80, "support": 85, "healer": 30, "tank": 60}},
    {"name": "Jiraiya", "village": "Коноха", "ratings": {"captain": 94, "vice": 90, "support": 78, "healer": 50, "tank": 82}},
    {"name": "Tsunade", "village": "Коноха", "ratings": {"captain": 93, "vice": 88, "support": 70, "healer": 98, "tank": 88}},
    {"name": "Orochimaru", "village": "Otogakure", "ratings": {"captain": 91, "vice": 87, "support": 80, "healer": 75, "tank": 70}},
    {"name": "Itachi Uchiha", "village": "Konoha/Akatsuki", "ratings": {"captain": 94, "vice": 96, "support": 88, "healer": 45, "tank": 75}},
    {"name": "Kisame Hoshigaki", "village": "Akatsuki", "ratings": {"captain": 82, "vice": 80, "support": 65, "healer": 25, "tank": 88}},
    {"name": "Deidara", "village": "Akatsuki", "ratings": {"captain": 75, "vice": 72, "support": 78, "healer": 20, "tank": 55}},
    {"name": "Sasori", "village": "Akatsuki", "ratings": {"captain": 78, "vice": 75, "support": 85, "healer": 30, "tank": 60}},
    {"name": "Hidan", "village": "Akatsuki", "ratings": {"captain": 70, "vice": 68, "support": 50, "healer": 15, "tank": 80}},
    {"name": "Kakuzu", "village": "Akatsuki", "ratings": {"captain": 80, "vice": 78, "support": 72, "healer": 40, "tank": 85}},
    {"name": "Pain/Nagato", "village": "Amegakure", "ratings": {"captain": 97, "vice": 92, "support": 90, "healer": 70, "tank": 85}},
    {"name": "Konan", "village": "Amegakure", "ratings": {"captain": 78, "vice": 80, "support": 82, "healer": 45, "tank": 65}},
    {"name": "Tobi/Obito", "village": "Akatsuki", "ratings": {"captain": 93, "vice": 90, "support": 85, "healer": 55, "tank": 80}},
    {"name": "Madara Uchiha", "village": "Konoha", "ratings": {"captain": 99, "vice": 97, "support": 92, "healer": 60, "tank": 95}},
    {"name": "Hashirama Senju", "village": "Konoha", "ratings": {"captain": 98, "vice": 95, "support": 88, "healer": 80, "tank": 90}},
    {"name": "Tobirama Senju", "village": "Konoha", "ratings": {"captain": 92, "vice": 90, "support": 85, "healer": 50, "tank": 78}},
    {"name": "Hiruzen Sarutobi", "village": "Konoha", "ratings": {"captain": 88, "vice": 85, "support": 82, "healer": 55, "tank": 70}},
    {"name": "Minato Namikaze", "village": "Konoha", "ratings": {"captain": 96, "vice": 94, "support": 80, "healer": 45, "tank": 72}},
    {"name": "Might Guy", "village": "Konoha", "ratings": {"captain": 85, "vice": 82, "support": 50, "healer": 25, "tank": 88}},
    {"name": "Asuma Sarutobi", "village": "Konoha", "ratings": {"captain": 80, "vice": 78, "support": 70, "healer": 35, "tank": 75}},
    {"name": "Kurenai Yuhi", "village": "Konoha", "ratings": {"captain": 72, "vice": 70, "support": 78, "healer": 40, "tank": 55}},
    {"name": "Yamato", "village": "Konoha", "ratings": {"captain": 78, "vice": 75, "support": 80, "healer": 45, "tank": 82}},
    {"name": "Sai", "village": "Konoha", "ratings": {"captain": 70, "vice": 68, "support": 75, "healer": 35, "tank": 60}},
    {"name": "Konohamaru Sarutobi", "village": "Konoha", "ratings": {"captain": 68, "vice": 65, "support": 62, "healer": 30, "tank": 58}},
    {"name": "Zabuza Momochi", "village": "Kiri", "ratings": {"captain": 78, "vice": 75, "support": 55, "healer": 20, "tank": 80}},
    {"name": "Haku", "village": "Kiri", "ratings": {"captain": 65, "vice": 62, "support": 70, "healer": 45, "tank": 50}},
    {"name": "Killer Bee", "village": "Kumo", "ratings": {"captain": 88, "vice": 85, "support": 72, "healer": 35, "tank": 85}},
    {"name": "A (Raikage)", "village": "Kumo", "ratings": {"captain": 90, "vice": 88, "support": 60, "healer": 30, "tank": 92}},
    {"name": "Darui", "village": "Kumo", "ratings": {"captain": 82, "vice": 80, "support": 78, "healer": 40, "tank": 75}},
    {"name": "Omoi", "village": "Kumo", "ratings": {"captain": 68, "vice": 65, "support": 70, "healer": 30, "tank": 62}},
    {"name": "Samui", "village": "Kumo", "ratings": {"captain": 70, "vice": 68, "support": 65, "healer": 35, "tank": 70}},
    {"name": "Onoki", "village": "Iwa", "ratings": {"captain": 85, "vice": 82, "support": 80, "healer": 45, "tank": 78}},
    {"name": "Kurotsuchi", "village": "Iwa", "ratings": {"captain": 75, "vice": 72, "support": 70, "healer": 40, "tank": 72}},
    {"name": "Akatsuchi", "village": "Iwa", "ratings": {"captain": 70, "vice": 68, "support": 62, "healer": 30, "tank": 85}},
    {"name": "Mei Terumi", "village": "Kiri", "ratings": {"captain": 86, "vice": 84, "support": 75, "healer": 50, "tank": 70}},
    {"name": "Ao", "village": "Kiri", "ratings": {"captain": 72, "vice": 70, "support": 68, "healer": 35, "tank": 65}},
    {"name": "Chojuro", "village": "Kiri", "ratings": {"captain": 68, "vice": 65, "support": 60, "healer": 30, "tank": 75}},
    {"name": "Suigetsu Hozuki", "village": "Kiri", "ratings": {"captain": 70, "vice": 68, "support": 65, "healer": 35, "tank": 72}},
    {"name": "Karin", "village": "Kusa", "ratings": {"captain": 55, "vice": 52, "support": 70, "healer": 80, "tank": 45}},
    {"name": "Juugo", "village": "None", "ratings": {"captain": 72, "vice": 70, "support": 55, "healer": 40, "tank": 82}},
    {"name": "Kimimaro", "village": "Otogakure", "ratings": {"captain": 75, "vice": 72, "support": 58, "healer": 25, "tank": 78}},
    {"name": "Kabuto Yakushi", "village": "Otogakure", "ratings": {"captain": 82, "vice": 80, "support": 85, "healer": 88, "tank": 65}},
    {"name": "Danzo Shimura", "village": "Konoha", "ratings": {"captain": 80, "vice": 78, "support": 75, "healer": 40, "tank": 70}},
    {"name": "Shisui Uchiha", "village": "Konoha", "ratings": {"captain": 88, "vice": 90, "support": 82, "healer": 40, "tank": 68}},
    {"name": "Nagato (young)", "village": "Amegakure", "ratings": {"captain": 75, "vice": 72, "support": 78, "healer": 55, "tank": 60}},
    {"name": "Yahiko", "village": "Amegakure", "ratings": {"captain": 72, "vice": 70, "support": 65, "healer": 35, "tank": 62}},
    {"name": "Zetsu", "village": "Akatsuki", "ratings": {"captain": 65, "vice": 62, "support": 80, "healer": 45, "tank": 55}},
    {"name": "Guren", "village": "Otogakure", "ratings": {"captain": 72, "vice": 70, "support": 68, "healer": 35, "tank": 65}},
    {"name": "Han", "village": "Iwa", "ratings": {"captain": 78, "vice": 75, "support": 60, "healer": 30, "tank": 80}},
    {"name": "Utakata", "village": "Kiri", "ratings": {"captain": 72, "vice": 70, "support": 68, "healer": 45, "tank": 58}},
    {"name": "Fu", "village": "Taki", "ratings": {"captain": 70, "vice": 68, "support": 65, "healer": 35, "tank": 60}},
    {"name": "Roshi", "village": "Iwa", "ratings": {"captain": 75, "vice": 72, "support": 62, "healer": 35, "tank": 78}},
    {"name": "Yugito Nii", "village": "Kumo", "ratings": {"captain": 78, "vice": 75, "support": 68, "healer": 40, "tank": 70}},
    {"name": "Fugaku Uchiha", "village": "Konoha", "ratings": {"captain": 85, "vice": 82, "support": 70, "healer": 35, "tank": 72}},
    {"name": "Kushina Uzumaki", "village": "Konoha", "ratings": {"captain": 78, "vice": 75, "support": 65, "healer": 55, "tank": 70}},
    {"name": "Nagato (Edo)", "village": "Amegakure", "ratings": {"captain": 90, "vice": 88, "support": 85, "healer": 65, "tank": 80}},
    {"name": "Hanzo", "village": "Amegakure", "ratings": {"captain": 88, "vice": 85, "support": 75, "healer": 50, "tank": 78}},
    {"name": "Third Raikage", "village": "Kumo", "ratings": {"captain": 92, "vice": 90, "support": 65, "healer": 30, "tank": 95}},
    {"name": "Mu", "village": "Iwa", "ratings": {"captain": 88, "vice": 85, "support": 80, "healer": 45, "tank": 75}},
    {"name": "Gengetsu Hozuki", "village": "Kiri", "ratings": {"captain": 85, "vice": 82, "support": 78, "healer": 50, "tank": 72}},
    {"name": "Rasa", "village": "Suna", "ratings": {"captain": 82, "vice": 80, "support": 72, "healer": 40, "tank": 75}},
    {"name": "Shikaku Nara", "village": "Konoha", "ratings": {"captain": 88, "vice": 86, "support": 90, "healer": 35, "tank": 55}},
    {"name": "Inoichi Yamanaka", "village": "Konoha", "ratings": {"captain": 75, "vice": 72, "support": 88, "healer": 50, "tank": 50}},
    {"name": "Choza Akimichi", "village": "Konoha", "ratings": {"captain": 72, "vice": 70, "support": 58, "healer": 30, "tank": 85}},
    {"name": "Hiashi Hyuga", "village": "Konoha", "ratings": {"captain": 82, "vice": 80, "support": 68, "healer": 40, "tank": 75}},
    {"name": "Hanabi Hyuga", "village": "Konoha", "ratings": {"captain": 65, "vice": 62, "support": 60, "healer": 35, "tank": 58}},
    {"name": "Iruka Umino", "village": "Konoha", "ratings": {"captain": 60, "vice": 58, "support": 55, "healer": 45, "tank": 50}},
    {"name": "Ebisu", "village": "Konoha", "ratings": {"captain": 55, "vice": 52, "support": 50, "healer": 30, "tank": 48}},
    {"name": "Anko Mitarashi", "village": "Konoha", "ratings": {"captain": 68, "vice": 65, "support": 62, "healer": 35, "tank": 60}},
    {"name": "Gai (8 gates)", "village": "Konoha", "ratings": {"captain": 92, "vice": 88, "support": 45, "healer": 20, "tank": 95}},
    {"name": "Naruto (KCM)", "village": "Konoha", "ratings": {"captain": 97, "vice": 94, "support": 80, "healer": 40, "tank": 90}},
    {"name": "Sasuke (Rinnegan)", "village": "Konoha", "ratings": {"captain": 96, "vice": 97, "support": 78, "healer": 35, "tank": 78}},
    {"name": "Sakura (100 healings)", "village": "Konoha", "ratings": {"captain": 85, "vice": 82, "support": 70, "healer": 98, "tank": 90}},
    {"name": "Boruto Uzumaki", "village": "Konoha", "ratings": {"captain": 75, "vice": 72, "support": 68, "healer": 35, "tank": 62}},
    {"name": "Sarada Uchiha", "village": "Konoha", "ratings": {"captain": 72, "vice": 70, "support": 65, "healer": 40, "tank": 58}},
    {"name": "Mitsuki", "village": "Konoha", "ratings": {"captain": 78, "vice": 75, "support": 72, "healer": 55, "tank": 65}},
    {"name": "Kawaki", "village": "Konoha", "ratings": {"captain": 82, "vice": 80, "support": 65, "healer": 40, "tank": 78}},
    {"name": "Momoshiki", "village": "Otsutsuki", "ratings": {"captain": 92, "vice": 90, "support": 85, "healer": 50, "tank": 82}},
    {"name": "Kinshiki", "village": "Otsutsuki", "ratings": {"captain": 85, "vice": 82, "support": 60, "healer": 30, "tank": 88}},
    {"name": "Kaguya Otsutsuki", "village": "Otsutsuki", "ratings": {"captain": 99, "vice": 97, "support": 95, "healer": 80, "tank": 92}},
    {"name": "Hagoromo Otsutsuki", "village": "Otsutsuki", "ratings": {"captain": 100, "vice": 98, "support": 95, "healer": 85, "tank": 90}},
    {"name": "Hamura Otsutsuki", "village": "Otsutsuki", "ratings": {"captain": 95, "vice": 93, "support": 88, "healer": 75, "tank": 85}},
    {"name": "Toneri Otsutsuki", "village": "Moon", "ratings": {"captain": 88, "vice": 85, "support": 80, "healer": 60, "tank": 78}},
    {"name": "Isshiki Otsutsuki", "village": "Otsutsuki", "ratings": {"captain": 98, "vice": 96, "support": 90, "healer": 55, "tank": 88}},
    {"name": "Jigen", "village": "Kara", "ratings": {"captain": 94, "vice": 92, "support": 82, "healer": 50, "tank": 85}},
    {"name": "Delta", "village": "Kara", "ratings": {"captain": 80, "vice": 78, "support": 70, "healer": 40, "tank": 75}},
    {"name": "Code", "village": "Kara", "ratings": {"captain": 88, "vice": 85, "support": 72, "healer": 45, "tank": 80}},
    {"name": "Shikadai Nara", "village": "Konoha", "ratings": {"captain": 68, "vice": 65, "support": 75, "healer": 30, "tank": 50}},
    {"name": "Chocho Akimichi", "village": "Konoha", "ratings": {"captain": 62, "vice": 60, "support": 55, "healer": 30, "tank": 72}},
    {"name": "Metal Lee", "village": "Konoha", "ratings": {"captain": 65, "vice": 62, "support": 48, "healer": 20, "tank": 78}},
    {"name": "Denki Kaminarimon", "village": "Konoha", "ratings": {"captain": 50, "vice": 48, "support": 72, "healer": 35, "tank": 42}},
    {"name": "Iwabe Yuino", "village": "Konoha", "ratings": {"captain": 58, "vice": 55, "support": 50, "healer": 25, "tank": 68}},
    {"name": "Wasabi Izuno", "village": "Konoha", "ratings": {"captain": 55, "vice": 52, "support": 58, "healer": 30, "tank": 52}},
    {"name": "Namida Suzumeno", "village": "Konoha", "ratings": {"captain": 48, "vice": 45, "support": 65, "healer": 55, "tank": 40}},
    {"name": "Sumire Kakei", "village": "Konoha", "ratings": {"captain": 62, "vice": 60, "support": 70, "healer": 45, "tank": 55}},
    {"name": "Mirai Sarutobi", "village": "Konoha", "ratings": {"captain": 70, "vice": 68, "support": 62, "healer": 40, "tank": 65}},
    {"name": "Moegi Kazamatsuri", "village": "Konoha", "ratings": {"captain": 65, "vice": 62, "support": 60, "healer": 35, "tank": 58}},
    {"name": "Udon Ise", "village": "Konoha", "ratings": {"captain": 58, "vice": 55, "support": 55, "healer": 30, "tank": 55}},
    {"name": "Pakura", "village": "Suna", "ratings": {"captain": 72, "vice": 70, "support": 68, "healer": 40, "tank": 62}},
    {"name": "Gari", "village": "Suna", "ratings": {"captain": 70, "vice": 68, "support": 65, "healer": 35, "tank": 65}},
    {"name": "Torune Aburame", "village": "Konoha", "ratings": {"captain": 68, "vice": 65, "support": 72, "healer": 40, "tank": 58}},
    {"name": "Fu Yamanaka", "village": "Konoha", "ratings": {"captain": 65, "vice": 62, "support": 75, "healer": 45, "tank": 52}},
    {"name": "Genma Shiranui", "village": "Konoha", "ratings": {"captain": 68, "vice": 65, "support": 62, "healer": 35, "tank": 58}},
    {"name": "Raido Namiashi", "village": "Konoha", "ratings": {"captain": 65, "vice": 62, "support": 58, "healer": 30, "tank": 60}},
    {"name": "Aoba Yamashiro", "village": "Konoha", "ratings": {"captain": 62, "vice": 60, "support": 70, "healer": 40, "tank": 50}},
    {"name": "Izumo Kamizuki", "village": "Konoha", "ratings": {"captain": 58, "vice": 55, "support": 55, "healer": 30, "tank": 55}},
    {"name": "Kotetsu Hagane", "village": "Konoha", "ratings": {"captain": 58, "vice": 55, "support": 55, "healer": 30, "tank": 55}},
    {"name": "Sakon/Ukon", "village": "Otogakure", "ratings": {"captain": 72, "vice": 70, "support": 65, "healer": 50, "tank": 68}},
    {"name": "Kidomaru", "village": "Otogakure", "ratings": {"captain": 68, "vice": 65, "support": 72, "healer": 25, "tank": 55}},
    {"name": "Tayuya", "village": "Otogakure", "ratings": {"captain": 65, "vice": 62, "support": 68, "healer": 30, "tank": 52}},
    {"name": "Jirobo", "village": "Otogakure", "ratings": {"captain": 62, "vice": 60, "support": 50, "healer": 25, "tank": 82}},
    {"name": "Dosu Kinuta", "village": "Otogakure", "ratings": {"captain": 55, "vice": 52, "support": 58, "healer": 25, "tank": 50}},
    {"name": "Zaku Abumi", "village": "Otogakure", "ratings": {"captain": 52, "vice": 50, "support": 55, "healer": 25, "tank": 48}},
    {"name": "Kin Tsuchi", "village": "Otogakure", "ratings": {"captain": 50, "vice": 48, "support": 52, "healer": 25, "tank": 45}},
    {"name": "Mizuki", "village": "Konoha", "ratings": {"captain": 45, "vice": 42, "support": 48, "healer": 25, "tank": 40}},
    {"name": "Hayate Gekko", "village": "Konoha", "ratings": {"captain": 58, "vice": 55, "support": 52, "healer": 30, "tank": 45}},
    {"name": "Baki", "village": "Suna", "ratings": {"captain": 75, "vice": 72, "support": 68, "healer": 35, "tank": 65}},
    {"name": "Yashamaru", "village": "Suna", "ratings": {"captain": 65, "vice": 62, "support": 60, "healer": 45, "tank": 52}},
    {"name": "Chiyo", "village": "Suna", "ratings": {"captain": 82, "vice": 78, "support": 75, "healer": 85, "tank": 55}},
    {"name": "Ebizo", "village": "Suna", "ratings": {"captain": 70, "vice": 68, "support": 62, "healer": 55, "tank": 50}},
    {"name": "Maki", "village": "Suna", "ratings": {"captain": 62, "vice": 60, "support": 58, "healer": 40, "tank": 55}},
    {"name": "Matsuri", "village": "Suna", "ratings": {"captain": 55, "vice": 52, "support": 55, "healer": 30, "tank": 50}},
    {"name": "Yodo", "village": "Suna", "ratings": {"captain": 52, "vice": 50, "support": 55, "healer": 30, "tank": 48}},
    {"name": "Shinki", "village": "Suna", "ratings": {"captain": 72, "vice": 70, "support": 65, "healer": 35, "tank": 68}},
    {"name": "Yodo (Boruto)", "village": "Suna", "ratings": {"captain": 58, "vice": 55, "support": 58, "healer": 30, "tank": 52}},
    {"name": "Araya", "village": "Suna", "ratings": {"captain": 60, "vice": 58, "support": 55, "healer": 30, "tank": 58}},
    {"name": "Toroi", "village": "Kumo", "ratings": {"captain": 55, "vice": 52, "support": 50, "healer": 25, "tank": 55}},
    {"name": "Ginkaku", "village": "Kumo", "ratings": {"captain": 78, "vice": 75, "support": 70, "healer": 40, "tank": 72}},
    {"name": "Kinkaku", "village": "Kumo", "ratings": {"captain": 80, "vice": 78, "support": 68, "healer": 35, "tank": 78}},
    {"name": "Danzo (ROOT)", "village": "Konoha", "ratings": {"captain": 82, "vice": 80, "support": 78, "healer": 42, "tank": 72}},
    {"name": "Sasuke (Hebi)", "village": "Konoha", "ratings": {"captain": 85, "vice": 88, "support": 72, "healer": 32, "tank": 70}},
    {"name": "Naruto (Sage Mode)", "village": "Konoha", "ratings": {"captain": 92, "vice": 88, "support": 78, "healer": 38, "tank": 85}},
    {"name": "Sasori (Human puppet)", "village": "Akatsuki", "ratings": {"captain": 76, "vice": 73, "support": 82, "healer": 28, "tank": 58}},
    {"name": "Black Zetsu", "village": "Akatsuki", "ratings": {"captain": 70, "vice": 68, "support": 85, "healer": 50, "tank": 52}},
    {"name": "White Zetsu", "village": "Akatsuki", "ratings": {"captain": 55, "vice": 52, "support": 65, "healer": 45, "tank": 48}},
    {"name": "Suigetsu (Edo)", "village": "Kiri", "ratings": {"captain": 72, "vice": 70, "support": 68, "healer": 38, "tank": 75}},
    {"name": "Mangetsu Hozuki", "village": "Kiri", "ratings": {"captain": 82, "vice": 80, "support": 75, "healer": 42, "tank": 78}},
    {"name": "Kushimaru Kuriarare", "village": "Kiri", "ratings": {"captain": 75, "vice": 72, "support": 65, "healer": 35, "tank": 70}},
    {"name": "Fuguki Suikazan", "village": "Kiri", "ratings": {"captain": 78, "vice": 75, "support": 68, "healer": 38, "tank": 72}},
    {"name": "Ameyuri Ringo", "village": "Kiri", "ratings": {"captain": 76, "vice": 73, "support": 65, "healer": 35, "tank": 68}},
    {"name": "Kakuzu (Edo)", "village": "Akatsuki", "ratings": {"captain": 82, "vice": 80, "support": 74, "healer": 42, "tank": 87}},
    {"name": "Asuma (Edo)", "village": "Konoha", "ratings": {"captain": 82, "vice": 80, "support": 72, "healer": 38, "tank": 78}},
    {"name": "Hiruzen (Edo)", "village": "Konoha", "ratings": {"captain": 90, "vice": 87, "support": 85, "healer": 58, "tank": 72}},
    {"name": "Tobirama (Edo)", "village": "Konoha", "ratings": {"captain": 94, "vice": 92, "support": 88, "healer": 52, "tank": 80}},
    {"name": "Hashirama (Edo)", "village": "Konoha", "ratings": {"captain": 99, "vice": 96, "support": 90, "healer": 82, "tank": 92}},
    {"name": "Madara (Edo)", "village": "Konoha", "ratings": {"captain": 99, "vice": 98, "support": 94, "healer": 62, "tank": 96}},
    {"name": "Kakashi (Six Paths)", "village": "Konoha", "ratings": {"captain": 95, "vice": 92, "support": 90, "healer": 48, "tank": 82}},
    {"name": "Naruto (Six Paths)", "village": "Konoha", "ratings": {"captain": 99, "vice": 96, "support": 85, "healer": 45, "tank": 92}},
    {"name": "Sasuke (Six Paths)", "village": "Konoha", "ratings": {"captain": 98, "vice": 99, "support": 82, "healer": 38, "tank": 80}},
]
